In [1]:
import pandas as pd
import numpy as np

# อ่านไฟล์

In [2]:
df =  pd.read_csv('student.csv')

# แสดงข้อมูล

In [3]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

# เก็บสำเนาข้อมูลต้นฉบับ

In [4]:
df_original = df.copy()
df_original

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-06

# ตรวจสอบค่าหายในแต่ละคอลัมน์

In [5]:
missing_counts = df.isnull().sum()
print("\n❌ ค่าหายในแต่ละคอลัมน์:")
for col, count in missing_counts[missing_counts > 0].items():
    percentage = (count / len(df)) * 100
    print(f"   - {col}: {count} ค่า ({percentage:.1f}%)")

❌ ค่าหายในแต่ละคอลัมน์:
   - ชื่อ: 1 ค่า (5.0%)
   - อายุ: 3 ค่า (15.0%)
   - เพศ: 2 ค่า (10.0%)
   - คณะ: 2 ค่า (10.0%)
   - GPA: 2 ค่า (10.0%)
   - ส่วนสูง_cm: 1 ค่า (5.0%)
   - น้ำหนัก_kg: 2 ค่า (10.0%)
   - ชั่วโมงเรียน_ต่อสัปดาห์: 2 ค่า (10.0%)

# แสดงข้อมูลก่อนลบ

In [6]:
print("ก่อนลบ")
print(df)

ก่อนลบ
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN             NaN  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง             NaN  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
2          NaN                     25.0      2024-01-13
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
10        68.0                      NaN      2024-01-07
11         NaN                     16.0      2023-12-26
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24
17        50.0                     27.0      2024-01-08
18        76.0                      NaN      2023-12-18
19        64.0                     23.0      2024-01-06

# เทคนิคการจัดการข้อมูลพื้นฐาน

# 1) การจัดการข้อมูลหาย

# 1.1 : ทำการ clean ข้อมูล ด้วยการลบแถวที่มีค่าหาย

ทำการลบชื่อที่ไม่มีค่าออกเพราะไม่สามารถเติมหรือเดาได้ เก็บไว้จะไม่มีประโยชน์ถ้าข้อมูลหาย

In [7]:
df_clean = df.dropna()

print(f"\nผลการลบ - ก่อนลบ {len(df)} แถว, หลังลบ {len(df_clean)} แถว")
print("หลังลบ (เหลือ 9 คน):")
print(df_clean)

ผลการลบ - ก่อนลบ 20 แถว, หลังลบ 14 แถว
หลังลบ (เหลือ 9 คน):
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24

# 1.2 : ทำการ clean ข้อมูลโดยการเตืมด้วยค่าเฉลี่ย

ทำการเติมด้วยค่าเฉลี่ยของ

อายุ : เพราะว่าค่าเฉลี่ยของอายุอาจไม่ได้กว้างมากเลยสามารถเติมได้ด้วยค่าเฉลี่ย

GPA : ค่า GPA เป็นเชิงปริมาณ ใช้ค่าเฉลี่ยรักษาสมดุลของข้อมูล

ส่วนสูง : เป็นค่าตัวเลขทางกายภาพเลยเหมาะกับค่าเฉลี่ย

น้ำหนัก : เป็นค่าตัวเลขทางกายภาพเลยเหมาะกับค่าเฉลี่ย

ชั่วโมงเรียน : เพื่อไม่ให้ค่าผิดเพี้ยนมาก

# แปลงค่าของ GPA ให้เป็น NaN

In [8]:
df_clean['GPA'] = df_clean['GPA'].replace(-1, np.nan)

/tmp/ipython-input-2760136785.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['GPA'] = df_clean['GPA'].replace(-1, np.nan)

In [9]:
mean_age = df_clean['อายุ'].mean()
mean_gpa = df_clean['GPA'].mean()
mean_height = df_clean['ส่วนสูง_cm'].mean()
mean_weight = df_clean['น้ำหนัก_kg'].mean()
mean_hour = df_clean['ชั่วโมงเรียน_ต่อสัปดาห์'].mean()

df_clean['อายุ'].fillna(mean_age, inplace=True)
df_clean['GPA'].fillna(mean_gpa, inplace=True)
df_clean['ส่วนสูง_cm'].fillna(mean_height, inplace=True)
df_clean['น้ำหนัก_kg'].fillna(mean_weight, inplace=True)
df_clean['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(mean_hour, inplace=True)




print(f"\nค่าเฉลี่ยอายุ - {mean_age:.1f} ปี")
print(f"\nค่าเฉลี่ย GPA - {mean_gpa:.1f} ")
print(f"\nค่าเฉลี่ยส่วนสูง - {mean_height:.1f} ซม")
print(f"\nค่าเฉลี่ยน้ำหนัก - {mean_weight:.1f} กก")
print(f"\nค่าเฉลี่ยชั่วโมงเรียน - {mean_hour:.1f} ชม")
print("หลังเติมค่า")
print(df_clean)

ค่าเฉลี่ยอายุ - 29.9 ปี

ค่าเฉลี่ย GPA - 3.5

ค่าเฉลี่ยส่วนสูง - 166.9 ซม

ค่าเฉลี่ยน้ำหนัก - 63.4 กก

ค่าเฉลี่ยชั่วโมงเรียน - 21.0 ชม
หลังเติมค่า
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ       GPA  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.210000
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.450000
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์  3.484615
4          64005      สมใจ   19.0       ญ           วิศวะ  3.890000
5          64006     กานต์  150.0     ชาย     Engineering  3.120000
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.500000
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.980000
8          64009    ชนาธิป   23.0       M            Arts  3.340000
9          64010      ดารา   21.0    หญิง           ศิลป์  3.560000
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.230000
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.450000
14         64015     พิมพ์   22.0  Female             Sci  3.670000
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.890000
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.010000

    ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0        170.0        65.0                     15.0      2024-01-23
1        165.0        58.0                     20.0      2024-02-05
3        168.0        70.0                     10.0      2023-12-30
4        160.0        52.0                     30.0      2024-01-27
5        172.0        75.0                     12.0      2023-12-23
6        158.0        48.0                     35.0      2024-01-05
7        180.0        82.0                     18.0      2024-01-23
8        163.0        55.0                     22.0      2024-02-11
9        167.0        60.0                     28.0      2024-01-03
12       169.0        72.0                     24.0      2023-12-26
13       164.0        54.0                     19.0      2024-01-08
14       162.0        56.0                     26.0      2024-02-06
15       173.0        78.0                     14.0      2024-01-20
16       166.0        62.0                     21.0      2024-01-24

/tmp/ipython-input-4152186063.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['อายุ'].fillna(mean_age, inplace=True)
/tmp/ipython-input-4152186063.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['อายุ'].fillna(mean_age, inplace=True)
/tmp/ipython-input-4152186063.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['GPA'].fillna(mean_gpa, inplace=True)
/tmp/ipython-input-4152186063.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['GPA'].fillna(mean_gpa, inplace=True)
/tmp/ipython-input-4152186063.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['ส่วนสูง_cm'].fillna(mean_height, inplace=True)
/tmp/ipython-input-4152186063.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['ส่วนสูง_cm'].fillna(mean_height, inplace=True)
/tmp/ipython-input-4152186063.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['น้ำหนัก_kg'].fillna(mean_weight, inplace=True)
/tmp/ipython-input-4152186063.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['น้ำหนัก_kg'].fillna(mean_weight, inplace=True)
/tmp/ipython-input-4152186063.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(mean_hour, inplace=True)
/tmp/ipython-input-4152186063.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(mean_hour, inplace=True)

# 2)การทำให้ข้อมูลเป็นมาตรฐาน


---

ข้อมูลที่ต้องทำให้เป็นมาตรฐาน คือ คณะ และ เพศ

In [10]:
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์', 'Sci', '']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts', 'Liberal Arts', '']:
        return 'ศิลปศาสตร์'
    elif name in ['วิศวกรรมศาสตร์', 'วิศวะ', 'วิศวกรรม', 'Engineering', 'วิศวฯ', ]:
        return 'วิศวกรรมศาสตร์'
    else:
        return name


def standardize_gender(name):
    if name in ['ชาย', 'ช', 'M', 'Male']:
        return 'ชาย'
    elif name in ['หญิง', 'ญ', 'F', 'Female']:
        return 'หญิง'
    else:
        return name



df_clean['คณะ'] = df_clean['คณะ'].apply(standardize_faculty)
df_clean['เพศ'] = df_clean['เพศ'].apply(standardize_gender)
df_clean

/tmp/ipython-input-2661362662.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['คณะ'] = df_clean['คณะ'].apply(standardize_faculty)
/tmp/ipython-input-2661362662.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['เพศ'] = df_clean['เพศ'].apply(standardize_gender)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.210000,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.450000,165.0,58.0,20.0,2024-02-05
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,3.484615,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.890000,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,วิศวกรรมศาสตร์,3.120000,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรมศาสตร์,4.500000,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.980000,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.340000,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.560000,167.0,60.0,28.0,2024-01-03
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.230000,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.450000,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.670000,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.890000,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.010000,166.0,62.0,21.0,2024-01-24

# การจัดการค่าผิดปกติ

---

ข้อมูลที่ต้องแก้ค่าผิดปกติคือ อายุ และ GPA

In [11]:
print("ข้อมูลต้นฉบับ")
print(df_clean)
print(f"\nค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - {df['อายุ'].mean():.2f}")
print(f"\nค่าเฉลี่ย GPA (รวมค่าผิดปกติ) - {df['GPA'].mean():.2f}")

ข้อมูลต้นฉบับ
    รหัสนักศึกษา      ชื่อ   อายุ   เพศ             คณะ       GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0   ชาย     วิทยาศาสตร์  3.210000       170.0
1          64002    สมหญิง   21.0  หญิง     วิทยาศาสตร์  3.450000       165.0
3          64004  สมศักดิ์   22.0   ชาย     วิทยาศาสตร์  3.484615       168.0
4          64005      สมใจ   19.0  หญิง  วิศวกรรมศาสตร์  3.890000       160.0
5          64006     กานต์  150.0   ชาย  วิศวกรรมศาสตร์  3.120000       172.0
6          64007     กิตติ   21.0  หญิง  วิศวกรรมศาสตร์  4.500000       158.0
7          64008      จิรา   20.0  หญิง      ศิลปศาสตร์  2.980000       180.0
8          64009    ชนาธิป   23.0   ชาย      ศิลปศาสตร์  3.340000       163.0
9          64010      ดารา   21.0  หญิง      ศิลปศาสตร์  3.560000       167.0
12         64013     บุญมี   20.0  หญิง  วิศวกรรมศาสตร์  3.230000       169.0
13         64014     ปรีชา   21.0   ชาย      ศิลปศาสตร์  3.450000       164.0
14         64015     พิมพ์   22.0  หญิง     วิทยาศาสตร์  3.670000       162.0
15         64016      ภูมิ   19.0   ชาย     วิทยาศาสตร์  3.890000       173.0
16         64017      มานี   20.0  หญิง  วิศวกรรมศาสตร์  3.010000       166.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24

ค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - 28.47

ค่าเฉลี่ย GPA (รวมค่าผิดปกติ) - 3.25

# ใช้ IQR (Interquartile Range)

---

จัดการค่าอายุ และ GPA

In [12]:
Q1 = df_clean['อายุ'].quantile(0.25)
Q3 = df_clean['อายุ'].quantile(0.75)
IQR = Q3 - Q1

# กำหนดขอบเขต
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR


# กรองค่าผิดปกติ
df_no_outliers = df_clean[(df_clean['อายุ'] >= lower_bound) & (df_clean['อายุ'] <= upper_bound)]


print(f"\nขอบเขตล่าง - {lower_bound}")
print(f"ขอบเขตบน - {upper_bound}")
print(f"\nข้อมูลหลังกรองค่าผิดปกติ")
print(df_no_outliers)
print(f"\nค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - {df_no_outliers['อายุ'].mean():.2f}")

ขอบเขตล่าง - 17.375
ขอบเขตบน - 24.375

ข้อมูลหลังกรองค่าผิดปกติ
    รหัสนักศึกษา      ชื่อ  อายุ   เพศ             คณะ       GPA  ส่วนสูง_cm  \
0          64001     สมชาย  20.0   ชาย     วิทยาศาสตร์  3.210000       170.0
1          64002    สมหญิง  21.0  หญิง     วิทยาศาสตร์  3.450000       165.0
3          64004  สมศักดิ์  22.0   ชาย     วิทยาศาสตร์  3.484615       168.0
4          64005      สมใจ  19.0  หญิง  วิศวกรรมศาสตร์  3.890000       160.0
6          64007     กิตติ  21.0  หญิง  วิศวกรรมศาสตร์  4.500000       158.0
7          64008      จิรา  20.0  หญิง      ศิลปศาสตร์  2.980000       180.0
8          64009    ชนาธิป  23.0   ชาย      ศิลปศาสตร์  3.340000       163.0
9          64010      ดารา  21.0  หญิง      ศิลปศาสตร์  3.560000       167.0
12         64013     บุญมี  20.0  หญิง  วิศวกรรมศาสตร์  3.230000       169.0
13         64014     ปรีชา  21.0   ชาย      ศิลปศาสตร์  3.450000       164.0
14         64015     พิมพ์  22.0  หญิง     วิทยาศาสตร์  3.670000       162.0
15         64016      ภูมิ  19.0   ชาย     วิทยาศาสตร์  3.890000       173.0
16         64017      มานี  20.0  หญิง  วิศวกรรมศาสตร์  3.010000       166.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24

ค่าเฉลี่ยอายุ (หลังกรองค่าผิดปกติ) - 20.69

In [14]:
Q1 = df_clean['GPA'].quantile(0.25)
Q3 = df_clean['GPA'].quantile(0.75)
IQR = Q3 - Q1

# กำหนดขอบเขต
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR


# กรองค่าผิดปกติ
df_no_outliers = df_clean[(df_clean['GPA'] >= lower_bound) & (df_clean['GPA'] <= upper_bound)]


print(f"\nขอบเขตล่าง - {lower_bound}")
print(f"ขอบเขตบน - {upper_bound}")
print(f"\nข้อมูลหลังกรองค่าผิดปกติ")
print(df_no_outliers)
print(f"\nค่าเฉลี่ยGPA (หลังกรองค่าผิดปกติ) - {df_no_outliers['GPA'].mean():.2f}")

ขอบเขตล่าง - 2.5737499999999995
ขอบเขตบน - 4.28375

ข้อมูลหลังกรองค่าผิดปกติ
    รหัสนักศึกษา      ชื่อ   อายุ   เพศ             คณะ       GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0   ชาย     วิทยาศาสตร์  3.210000       170.0
1          64002    สมหญิง   21.0  หญิง     วิทยาศาสตร์  3.450000       165.0
3          64004  สมศักดิ์   22.0   ชาย     วิทยาศาสตร์  3.484615       168.0
4          64005      สมใจ   19.0  หญิง  วิศวกรรมศาสตร์  3.890000       160.0
5          64006     กานต์  150.0   ชาย  วิศวกรรมศาสตร์  3.120000       172.0
7          64008      จิรา   20.0  หญิง      ศิลปศาสตร์  2.980000       180.0
8          64009    ชนาธิป   23.0   ชาย      ศิลปศาสตร์  3.340000       163.0
9          64010      ดารา   21.0  หญิง      ศิลปศาสตร์  3.560000       167.0
12         64013     บุญมี   20.0  หญิง  วิศวกรรมศาสตร์  3.230000       169.0
13         64014     ปรีชา   21.0   ชาย      ศิลปศาสตร์  3.450000       164.0
14         64015     พิมพ์   22.0  หญิง     วิทยาศาสตร์  3.670000       162.0
15         64016      ภูมิ   19.0   ชาย     วิทยาศาสตร์  3.890000       173.0
16         64017      มานี   20.0  หญิง  วิศวกรรมศาสตร์  3.010000       166.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24

ค่าเฉลี่ยGPA (หลังกรองค่าผิดปกติ) - 3.41

# Feature Engineering - การสร้างคุณลักษณะใหม่

---



# 1) One-Hot Encoding แปลงข้อมูลประเภทเป็นตัวเลข

In [16]:
# ทำ One-Hot Encoding
data_encoded = pd.get_dummies(df_clean, columns=["คณะ"])
print(data_encoded*1)

    รหัสนักศึกษา      ชื่อ   อายุ   เพศ       GPA  ส่วนสูง_cm  น้ำหนัก_kg  \
0          64001     สมชาย   20.0   ชาย  3.210000       170.0        65.0
1          64002    สมหญิง   21.0  หญิง  3.450000       165.0        58.0
3          64004  สมศักดิ์   22.0   ชาย  3.484615       168.0        70.0
4          64005      สมใจ   19.0  หญิง  3.890000       160.0        52.0
5          64006     กานต์  150.0   ชาย  3.120000       172.0        75.0
6          64007     กิตติ   21.0  หญิง  4.500000       158.0        48.0
7          64008      จิรา   20.0  หญิง  2.980000       180.0        82.0
8          64009    ชนาธิป   23.0   ชาย  3.340000       163.0        55.0
9          64010      ดารา   21.0  หญิง  3.560000       167.0        60.0
12         64013     บุญมี   20.0  หญิง  3.230000       169.0        72.0
13         64014     ปรีชา   21.0   ชาย  3.450000       164.0        54.0
14         64015     พิมพ์   22.0  หญิง  3.670000       162.0        56.0
15         64016      ภูมิ   19.0   ชาย  3.890000       173.0        78.0
16         64017      มานี   20.0  หญิง  3.010000       166.0        62.0

    ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน  คณะ_วิทยาศาสตร์  \
0                      15.0      2024-01-23                1
1                      20.0      2024-02-05                1
3                      10.0      2023-12-30                1
4                      30.0      2024-01-27                0
5                      12.0      2023-12-23                0
6                      35.0      2024-01-05                0
7                      18.0      2024-01-23                0
8                      22.0      2024-02-11                0
9                      28.0      2024-01-03                0
12                     24.0      2023-12-26                0
13                     19.0      2024-01-08                0
14                     26.0      2024-02-06                1
15                     14.0      2024-01-20                1
16                     21.0      2024-01-24                0

    คณะ_วิศวกรรมศาสตร์  คณะ_ศิลปศาสตร์
0                    0               0
1                    0               0
3                    0               0
4                    1               0
5                    1               0
6                    1               0
7                    0               1
8                    0               1
9                    0               1
12                   1               0
13                   0               1
14                   0               0
15                   0               0
16                   1               0

# 2) การสร้าง Feature จากวันเวลา โดยใช้ข้อมูลจาก student.csv

In [17]:
##ตัวอย่างที่ต้องการให้แสดงโดยวิธีการทำงานโดยการสร้าง Featureจากวันเวลา
# ทำการแปลงวันที่ลงทะเบียนเป็นชนิดวันที่
df_clean['วันที่ลงทะเบียน'] = pd.to_datetime(df_clean['วันที่ลงทะเบียน'])

# แปลงชั่วโมงเรียนต่อสัปดาห์ให้เป็นตัวเลข (ถ้าแปลงไม่ได้จะกลายเป็นค่าว่าง)
df_clean['ชั่วโมงเรียน_ต่อสัปดาห์'] = pd.to_numeric(df_clean['ชั่วโมงเรียน_ต่อสัปดาห์'], errors='coerce')

# ใช้ค่าชั่วโมงเรียนต่อสัปดาห์แทนชั่วโมง
df_clean['ชั่วโมง'] = df_clean['ชั่วโมงเรียน_ต่อสัปดาห์']

# แบ่งช่วงชั่วโมงเรียนเป็นระดับต่างๆ
df_clean['ช่วงเวลา'] = pd.cut(df_clean['ชั่วโมงเรียน_ต่อสัปดาห์'],
                          bins=[0, 5, 10, 15, 20, float('inf')],
                          labels=['ไม่มี', 'น้อย', 'ปานกลาง', 'มาก', 'มากที่สุด'])

# แสดงข้อมูลที่สำคัญ
print(df_clean[['วันที่ลงทะเบียน', 'ชั่วโมง', 'ช่วงเวลา']].head())

  วันที่ลงทะเบียน  ชั่วโมง   ช่วงเวลา
0      2024-01-23     15.0    ปานกลาง
1      2024-02-05     20.0        มาก
3      2023-12-30     10.0       น้อย
4      2024-01-27     30.0  มากที่สุด
5      2023-12-23     12.0    ปานกลาง

/tmp/ipython-input-4292572812.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['วันที่ลงทะเบียน'] = pd.to_datetime(df_clean['วันที่ลงทะเบียน'])
/tmp/ipython-input-4292572812.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['ชั่วโมงเรียน_ต่อสัปดาห์'] = pd.to_numeric(df_clean['ชั่วโมงเรียน_ต่อสัปดาห์'], errors='coerce')
/tmp/ipython-input-4292572812.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['ชั่วโมง'] = df_clean['ชั่วโมงเรียน_ต่อสัปดาห์']
/tmp/ipython-input-4292572812.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['ช่วงเวลา'] = pd.cut(df_clean['ชั่วโมงเรียน_ต่อสัปดาห์'],

# 3) การรวม Features โดยใช้ข้อมูลจาก student.csv

In [18]:
# สร้าง BMI
df_clean['BMI'] = df_clean['น้ำหนัก_kg'] / (df_clean['ส่วนสูง_cm']/100)**2
df_clean['สุขภาพ'] = pd.cut(df_clean['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

print(df_clean[['ชื่อ', 'BMI', 'สุขภาพ']])

        ชื่อ        BMI สุขภาพ
0      สมชาย  22.491349   ปกติ
1     สมหญิง  21.303949   ปกติ
3   สมศักดิ์  24.801587   ปกติ
4       สมใจ  20.312500   ปกติ
5      กานต์  25.351541   อ้วน
6      กิตติ  19.227688   ปกติ
7       จิรา  25.308642   อ้วน
8     ชนาธิป  20.700817   ปกติ
9       ดารา  21.513859   ปกติ
12     บุญมี  25.209201   อ้วน
13     ปรีชา  20.077335   ปกติ
14     พิมพ์  21.338211   ปกติ
15      ภูมิ  26.061679   อ้วน
16      มานี  22.499637   ปกติ

/tmp/ipython-input-878537590.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['BMI'] = df_clean['น้ำหนัก_kg'] / (df_clean['ส่วนสูง_cm']/100)**2
/tmp/ipython-input-878537590.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['สุขภาพ'] = pd.cut(df_clean['BMI'],

# Workshop

In [19]:
# สร้าง dataset ตัวอย่าง
import pandas as pd
import numpy as np

# ข้อมูลดิบที่มีปัญหา
raw_data = {
    'รหัสนักศึกษา': ['64001', '64002', '64003', '64004', '64005'],
    'ชื่อ': ['สมชาย', 'สมหญิง', None, 'สมศักดิ์', 'สมใจ'],
    'คณะ': ['วิทย์', 'ศิลปศาสตร์', 'วิทยาศาสตร์', 'Arts', 'วิศวะ'],
    'ชั้นปี': [2, 3, 2, None, 4],
    'GPA': [3.2, 3.8, -1, 2.9, 4.5],  # -1 และ 4.5 ผิดปกติ
    'กิจกรรม': ['กีฬา', 'ดนตรี', 'กีฬา,ดนตรี', None, 'อาสา'],
    'เวลาเข้าร่วม': ['08:00', '9.30', '08:30', '08:00', None]
}

df_student = pd.DataFrame(raw_data)
print("=== ข้อมูลดิบ ===")
print(df_student)
print("\nปัญหาที่พบ")
print(f"- ข้อมูลหาย - {df_student.isnull().sum().sum()} ค่า")
print(f"- GPA ผิดปกติ - {df_student[(df_student['GPA'] < 0) | (df_student['GPA'] > 4)]['GPA'].tolist()}")

=== ข้อมูลดิบ ===
  รหัสนักศึกษา      ชื่อ          คณะ  ชั้นปี  GPA     กิจกรรม เวลาเข้าร่วม
0        64001     สมชาย        วิทย์     2.0  3.2        กีฬา        08:00
1        64002    สมหญิง   ศิลปศาสตร์     3.0  3.8       ดนตรี         9.30
2        64003      None  วิทยาศาสตร์     2.0 -1.0  กีฬา,ดนตรี        08:30
3        64004  สมศักดิ์         Arts     NaN  2.9        None        08:00
4        64005      สมใจ        วิศวะ     4.0  4.5        อาสา         None

ปัญหาที่พบ
- ข้อมูลหาย - 4 ค่า
- GPA ผิดปกติ - [-1.0, 4.5]

# **ทำความสะอาดข้อมูลในส่วนของ work shop แต่ใช้ไฟล์ข้อมูล student.csv**

In [20]:
# Step 1 - จัดการข้อมูลหาย
# ชื่อที่หาย - ใช้ "ไม่ระบุ"
df_student['ชื่อ'].fillna('ไม่ระบุ', inplace=True)

# ชั้นปีที่หาย - ใช้ค่าที่พบบ่อยที่สุด
mode_year = df_student['ชั้นปี'].mode()[0]
df_student['ชั้นปี'].fillna(mode_year, inplace=True)

# กิจกรรมที่หาย - ใช้ "ไม่ได้เข้าร่วม"
df_student['กิจกรรม'].fillna('ไม่ได้เข้าร่วม', inplace=True)

# Step 2 - แก้ไข GPA ผิดปกติ
df_student.loc[df_student['GPA'] < 0, 'GPA'] = np.nan
df_student.loc[df_student['GPA'] > 4, 'GPA'] = 4.0
mean_gpa = df_student['GPA'].mean()
df_student['GPA'].fillna(mean_gpa, inplace=True)

# Step 3 - ทำให้ชื่อคณะเป็นมาตรฐาน
faculty_mapping = {
    'วิทย์': 'วิทยาศาสตร์',
    'วิทยาศาสตร์': 'วิทยาศาสตร์',
    'ศิลปศาสตร์': 'ศิลปศาสตร์',
    'Arts': 'ศิลปศาสตร์',
    'วิศวะ': 'วิศวกรรมศาสตร์'
}
df_student['คณะ'] = df_student['คณะ'].map(faculty_mapping)

# Step 4 - แปลงเวลาให้เป็นรูปแบบเดียวกัน
def standardize_time(time_str):
    if pd.isna(time_str):
        return '08:00'  # ค่าเริ่มต้น
    time_str = str(time_str).replace('.', ':')
    if len(time_str.split(':')[0]) == 1:
        time_str = '0' + time_str
    return time_str

df_student['เวลาเข้าร่วม'] = df_student['เวลาเข้าร่วม'].apply(standardize_time)

print("\n=== ข้อมูลหลังทำความสะอาด ===")
print(df_student)

=== ข้อมูลหลังทำความสะอาด ===
  รหัสนักศึกษา      ชื่อ             คณะ  ชั้นปี    GPA         กิจกรรม  \
0        64001     สมชาย     วิทยาศาสตร์     2.0  3.200            กีฬา
1        64002    สมหญิง      ศิลปศาสตร์     3.0  3.800           ดนตรี
2        64003   ไม่ระบุ     วิทยาศาสตร์     2.0  3.475      กีฬา,ดนตรี
3        64004  สมศักดิ์      ศิลปศาสตร์     2.0  2.900  ไม่ได้เข้าร่วม
4        64005      สมใจ  วิศวกรรมศาสตร์     4.0  4.000            อาสา

  เวลาเข้าร่วม
0        08:00
1        09:30
2        08:30
3        08:00
4        08:00

/tmp/ipython-input-4009819203.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_student['ชื่อ'].fillna('ไม่ระบุ', inplace=True)
/tmp/ipython-input-4009819203.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_student['ชั้นปี'].fillna(mode_year, inplace=True)
/tmp/ipython-input-4009819203.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_student['กิจกรรม'].fillna('ไม่ได้เข้าร่วม', inplace=True)
/tmp/ipython-input-4009819203.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_student['GPA'].fillna(mean_gpa, inplace=True)

In [21]:
# Feature 1 - แปลงเวลาเป็นช่วงเวลา
df_student['ชั่วโมง'] = pd.to_datetime(df_student['เวลาเข้าร่วม'], format='%H:%M').dt.hour
df_student['ช่วงเวลา'] = pd.cut(df_student['ชั่วโมง'],
                                 bins=[0, 9, 12, 24],
                                 labels=['เช้า', 'สาย', 'บ่าย'])

# Feature 2 - นับจำนวนกิจกรรม
df_student['จำนวนกิจกรรม'] = df_student['กิจกรรม'].apply(
    lambda x: len(x.split(',')) if x != 'ไม่ได้เข้าร่วม' else 0
)

# Feature 3 - จัดกลุ่มผลการเรียน
df_student['ระดับผลการเรียน'] = pd.cut(df_student['GPA'],
                                        bins=[0, 2.0, 3.0, 3.5, 4.0],
                                        labels=['ต่ำ', 'ปานกลาง', 'ดี', 'ดีมาก'])

# Feature 4 - One-Hot Encoding สำหรับคณะ
df_encoded = pd.get_dummies(df_student, columns=['คณะ'], prefix='คณะ')

print("\n=== ข้อมูลหลัง Feature Engineering ===")
print(df_encoded[['รหัสนักศึกษา', 'ช่วงเวลา', 'จำนวนกิจกรรม', 'ระดับผลการเรียน']])
print("\nคอลัมน์ทั้งหมด")
print(df_encoded.columns.tolist())

=== ข้อมูลหลัง Feature Engineering ===
  รหัสนักศึกษา ช่วงเวลา  จำนวนกิจกรรม ระดับผลการเรียน
0        64001     เช้า             1              ดี
1        64002     เช้า             1           ดีมาก
2        64003     เช้า             2              ดี
3        64004     เช้า             0         ปานกลาง
4        64005     เช้า             1           ดีมาก

คอลัมน์ทั้งหมด
['รหัสนักศึกษา', 'ชื่อ', 'ชั้นปี', 'GPA', 'กิจกรรม', 'เวลาเข้าร่วม', 'ชั่วโมง', 'ช่วงเวลา', 'จำนวนกิจกรรม', 'ระดับผลการเรียน', 'คณะ_วิทยาศาสตร์', 'คณะ_วิศวกรรมศาสตร์', 'คณะ_ศิลปศาสตร์']